print ("Hello! May I ask what is your name?")
name = input("Enter your name:")
print("Hello" +name +"! "+"Welcome to our Python class" + "!")
print()
print("Hello, May I ask what is your name?")
name = input("Enter your name:")
print(f"Hello {name}! Welcome to our Python class")